#!/bin/sh

zksh=false
editor=vim

die()
{
	[ $# -eq 0 ] && exit 1
	
	[ $# -gt 1 ] && \
	echo "error initiated at line $1 : 
	$2" 1>&2 || \
	echo "$1" 1>&2
	
	exit 1
}

while [ $# -gt 0 ]; do
	case "$1" in
		--help)
			man poshinit
			exit 0
		;;

		*)
			die $LINENO "Invalid arg : $1"
		;;
	esac
done

cd $HOME || die $LINENO '`cd $HOME` failed. Aborting  : - ('

echo 'I shall delete 3 globs under your $HOME :  .bash* .zsh* .shell*'
echo 'If you are okay with that, press Enter. Else hit Ctrl+C to abort.'
read dummy

rm -rf .bash* .zsh* .shell*

ok=false

while [ $ok = false ]; do
	echo "I am using $editor as your preferred text editor"
	echo "Is that okay with you ? (y/n):"

	read answer
	case "$answer" in
		y|Y|yes)
			ok=true
		;;
		
		n|N|no)
			echo "Enter the command to use as editor"
			read editor
		;;

		*)
			die $LINENO 'I could not make any sense of that. Aborting  : - ('
		;;
	esac
done

[ -z "$editor" ] && die $LINENO '$editor is null. Aborting  : - ('

if ! which "$editor" > /dev/null; then
	echo 'Warning: bad `which $editor`' 1>&2
	echo 'I am continuing with setup as such.' 1>&2
	echo 'You can change your editor via ~/.shell/exports' 1>&2
	echo 'Press Enter to continue'
	read dummy
fi

echo "Z shell by default begins array indexing at 1."
echo "Some system programs assume the default behaviour."
echo "But, if you need, you can change the default below."
echo "Would you like your Z to begin arrays at 0 (Bash-compatible) ? (y/n):"

read answer
case "$answer" in
	y|Y|yes)
		zksh=true
	;;
	
	n|N|no)
		zksh=false
	;;

	*)
		die $LINENO 'I could not make any sense of that. Aborting  : - ('
	;;
esac

set -e
clear
mkdir .shell

{
cat << 'EOF_aliases'
# This file is meant for implementation-independent aliases.
# Put OS-specific aliases (eg: ls) in level_2

alias editor="$EDITOR"
alias p="cd .."
alias p2="cd ../.."
alias rf="rm -rf"

##### Above this line is what was pre-packaged. Below is the user section ######

EOF_aliases
} > .shell/aliases

{
cat << 'EOF_exports'
# This file is meant for implementation-independent exports.
# Put OS-specific exports in level_2

export PATH=$PATH:$HOME/bin

##### Above this line is what was pre-packaged. Below is the user section ######

EOF_exports
} > .shell/exports

echo "export EDITOR=$editor" >> .shell/exports

{
cat << 'EOF_functions'
# This file is meant for implementation-independent functions.
# Put OS-specific functions in level_2

##### Above this line is what was pre-packaged. Below is the user section ######

EOF_functions
} > .shell/functions

echo > .shell/uponlogin
echo > .shell/uponlogout

echo '[ -e ~/.shell/level_1.all ] && . ~/.shell/level_1.all' > .shellrc
echo '[ -e ~/.shell/uponlogin ] && . ~/.shell/uponlogin' >> .shellrc

{
cat << 'EOF_bash'
PS1='`pwd` <<: '
HISTFILE="$HOME/.bash_history"
[ -e ~/.shellrc ] && . ~/.shellrc
[ -e ~/.shell/uponlogout ] && ln -sf ~/.shell/uponlogout ~/.bash_logout
EOF_bash
} > .bashrc

ln .bashrc .bash_profile

> .zshrc
[ $zksh = true ] && echo "setopt KSH_ARRAYS" >> .zshrc

{
cat << 'EOF_zsh'
PROMPT='%d <<: '
HISTFILE="$HOME/.zhistory"
setopt hist_ignore_all_dups

bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey "\e[5~" beginning-of-history
bindkey "\e[6~" end-of-history
bindkey "\e[3~" delete-char
bindkey "\e[2~" quoted-insert
bindkey "\e[5C" forward-word
bindkey "\eOc" emacs-forward-word
bindkey "\e[5D" backward-word
bindkey "\eOd" emacs-backward-word
bindkey "\ee[C" forward-word
bindkey "\ee[D" backward-word
bindkey "\^H" backward-delete-word
bindkey "\e[8~" end-of-line
bindkey "\e[7~" beginning-of-line
bindkey "\eOH" beginning-of-line
bindkey "\eOF" end-of-line
bindkey '^i' expand-or-complete-prefix
bindkey "\e[H" beginning-of-line
bindkey "\e[F" end-of-line

[ -e ~/.shellrc ] && . ~/.shellrc
[ -e ~/.shell/uponlogout ] && ln -sf ~/.shell/uponlogout ~/.zlogout
EOF_zsh
} >> .zshrc

{
cat << 'EOF1_all'
echo "$-" | grep -q 'i' || return

# Exported definitions always get processed first :
[ -f ~/.shell/exports ] && . ~/.shell/exports      # define EDITOR here
[ -f ~/.shell/aliases ] && . ~/.shell/aliases      # define editor here
[ -f ~/.shell/functions ] && . ~/.shell/functions

alias editor="$EDITOR"                             # restated, after ~/.aliases
alias A="editor ~/.shell/aliases"
alias AA=". ~/.shell/aliases"
alias E="editor ~/.shell/exports"
alias EE=". ~/.shell/exports"
alias F="editor ~/.shell/functions"
alias FF=". ~/.shell/functions"
alias I="editor ~/.shell/uponlogin"
alias II=". ~/.shell/uponlogin"
alias O="editor ~/.shell/uponlogout"
alias OO=". ~/.shell/uponlogout"
alias L1="editor ~/.shell/level_1.all"
alias L2="editor ~/.shell/level_2"

# End of level_1 (Unix) global configuration.
# All stuff below is for level_2, which branches for
# freebsd / linux / cygwin :

if [ -L ~/.shell/level_2 ]; then
	for dist in freebsd linux cygwin; do
		if uname | grep -q -i $dist; then
			if ! readlink ~/.shell/level_2 | grep -q -i $dist; then
				if [ -f ~/.shell/level_2.${dist} ]; then
					cd ~/.shell
					ln -sf level_2.${dist} level_2
					1>/dev/null cd -
				else
					rm -f ~/.shell/level_2
				fi
			fi

			break
		fi
	done
else
	if ! [ -f ~/.shell/level_2 ]; then
		dist=`uname | tr '[:upper:]' '[:lower:]' | sed 's|_.*||'`
		
		if [ -f ~/.shell/level_2.${dist} ]; then
			cd ~/.shell
			ln -s level_2.${dist} level_2
			1>/dev/null cd -
		fi
	fi
fi

[ -e ~/.shell/level_3 ] && rm -f ~/.shell/level_3
[ -e ~/.shell/level_2 ] && . ~/.shell/level_2
EOF1_all
} > .shell/level_1.all

{
cat << 'EOF2_freebsd'
# This file is meant for FreeBSD-specific definitions.
# Put implementation-independent definitions in the files
# [$HOME/.shell/]aliases|exports|functions

alias ls="ls -G"
alias pfind="pkg search"
alias pin="pkg install"
alias pls="pkg query %n"

# Restart your terminal to have changes to this file take effect #
EOF2_freebsd
} > .shell/level_2.freebsd

{
cat << 'EOF2_cygwin'
# This file is meant for Cygwin-specific definitions.
# Put implementation-independent definitions in the files
# [$HOME/.shell/]aliases|exports|functions

alias ls="ls --color=auto"

# Restart your terminal to have changes to this file take effect #
EOF2_cygwin
} > .shell/level_2.cygwin

{
cat << 'EOF2_linux'
# This file is meant for Linux-specific definitions.
# Put implementation-independent definitions in the files
# [$HOME/.shell/]aliases|exports|functions

# <distro-independent-definitions>
alias ls="ls --color=auto"
alias L3="editor ~/.shell/level_3"
# </distro-independent-definitions>

# End of distro-independent block.
# All stuff below is for Level 3, which branches for distro flavours:
# arch / debian / redhat

flavour=""

if [ -f /etc/arch-release ]; then
	flavour=arch
elif [ -f /etc/debian_version ]; then
	flavour=debian
elif [ -f /etc/redhat-release ]; then
	flavour=redhat
fi

[ -n "$flavour" ] || return

if [ -L ~/.shell/level_3 ]; then
	if ! readlink ~/.shell/level_3 | grep -q -i $flavour; then
		if [ -f ~/.shell/level_3.${flavour} ]; then
			cd ~/.shell
			ln -sf level_3.${flavour} level_3
			1>/dev/null cd -
		else
			rm -f ~/.shell/level_3
		fi
	fi
else
	if ! [ -f ~/.shell/level_3 ]; then
		if [ -f ~/.shell/level_3.${flavour} ]; then
			cd ~/.shell
			ln -s level_3.${flavour} level_3
			1>/dev/null cd -
		fi
	fi
fi

[ -e ~/.shell/level_3 ] && . ~/.shell/level_3

# Restart your terminal to have changes to this file take effect #
EOF2_linux
} > .shell/level_2.linux

{
cat << 'EOF3_arch'
alias pfind="pacman -Ss"
alias pin="pacman -S"
alias pls="pacman --query"

# Restart your terminal to have changes to this file take effect #
EOF3_arch
} > .shell/level_3.arch

{
cat << 'EOF3_debian'
alias pfind="apt search"
alias pin="apt install"
alias pls="apt list --installed"

# Restart your terminal to have changes to this file take effect #
EOF3_debian
} > .shell/level_3.debian

{
cat << 'EOF3_redhat'
alias pfind="yum search"
alias pin="yum install"
alias pls="yum list installed"

# Restart your terminal to have changes to this file take effect #
EOF3_redhat
} > .shell/level_3.redhat

set +e

{
cat << 'EOF_final'
I have created 3 kinds of aliases, as noted underneath.

A) implementation-independent :     | C) implementation-dependent :
(under $HOME/.shell/aliases)        | (under the highest possible level file)
alias editor="$EDITOR"              | < Level 1 is the shared highest level >
alias p="cd .."                     |
alias p2="cd ../.."                 | c1)) For FreeBSD (under .shell/level_2)
alias rf="rm -rf"                   | alias ls="ls -G"
                                    | alias pfind="pkg search"
B) poshinit-specific :              | alias pin="pkg install"
(under $HOME/.shell/level_1.all)    | alias pls="pkg query %n"
alias A="editor ~/.shell/aliases"   |
alias AA=". ~/.shell/aliases"       | c2)) For Cygwin (under .shell/level_2)
alias E="editor ~/.shell/exports"   | alias ls="ls --color=auto"
alias EE=". ~/.shell/exports"       |
alias F="editor ~/.shell/functions" | c3)) Linux (distro-independent -> level_2)
alias FF=". ~/.shell/functions"     | alias ls="ls --color=auto"
alias I="editor ~/.shell/uponlogin" | alias L3="editor ~/.shell/level_3"
alias II=". ~/.shell/uponlogin"     |
alias O="editor ~/.shell/uponlogout"| c4)) Linux (distro-dependent -> level_3)
alias OO=". ~/.shell/uponlogout"    | alias pfind="<search for package>"
alias L1="editor ~/.shell/level_1"  | alias pin="<install package>"
alias L2="editor ~/.shell/level_2"  | alias pls="<list installed package>"

Portable shell initialization layout created successfully.
To have it take effect, logout and login again (or restart your terminal).
This complete message has been saved as $HOME/poshinit-msg.txt
EOF_final
} | tee poshinit-msg.txt

exit 0
